---
title: '&#39;Catch&#39; dışında görünemez bir &#39;deneyin&#39; deyimi'
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 346852cbd5693fbafe25413291ae284de3692875
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 05/04/2018
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39;Catch&#39; dışında görünemez bir &#39;deneyin&#39; deyimi
`Catch` içinde yer almalıdır bir `Try...Catch...Finally` deyimi bloğu. Ya da bir gereksiz sahip `Catch` deyiminde, `Try` bloğu veya `Catch` deyimi görünüyor ilgili sınırları dışında `Try` bloğu.  
  
 **Hata Kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Silme `Catch` gereksiz veya içine koyun deyimi bir `Try...Catch...Finally` deyimi bloğu.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
