---
title: "&#39; Son olarak &#39; dışında görünemez bir &#39; Try &#39; deyimi"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 259df1345b443d5023ebecd457c81167d0799fe0
ms.sourcegitcommit: 34ec7753acf76f90a0fa845235ef06663dc9e36e
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/21/2017
---
# <a name="39finally39-cannot-appear-outside-a-39try39-statement"></a>&#39; Son olarak &#39; dışında görünemez bir &#39; Try &#39; deyimi
`Finally`tamamlamak için kullanılan bir `Try...Catch...Finally` engelle; Bu nedenle, yalnızca bir kez bloğun sonunda yer alabilir. Ya da bir gereksiz sahip `Finally`, veya `Finally` deyimi görünüyor ilgili sınırları dışında `Try` bloğu.  
  
 **Hata Kimliği:** BC30382  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Bulun ve gereksiz kaldırmak `Finally` deyimi.  
  
2.  Taşıma `Finally` kodunuzda uygun konuma deyimi.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
