---
title: "&#39; Catch &#39; hiçbir zaman çünkü ulaşıldığında Blok &#39; &lt;Ad1&gt;&#39; devraldığı &#39;&lt; ad2&gt;&#39;"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 699f2ef1ff9d554bb9203631017b424ab887ab93
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/19/2018
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39; Catch &#39; hiçbir zaman çünkü ulaşıldığında Blok &#39; &lt;Ad1&gt;&#39; devraldığı &#39;&lt; ad2&gt;&#39;
A `Catch` kodu blokta hiç ulaşılamadı.  
  
 Varsayılan olarak, bu iletiyi bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak davranma daha fazla bilgi için bkz: [yapılandırma uyarılarını Visual Basic'te](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Hata Kimliği:** BC42029  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
-   Yabancı kaldırmak `Catch` bloğu.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Nasıl yapılır: Test kodu ile bir Try... Visual Basic'te catch bloğu](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
