---
title: . NET'te g/ç hataları işleme
ms.date: 08/27/2018
ms.technology: dotnet-standard
ms.topic: article
helpviewer_keywords:
- I/O, exception handling
- I/O, errors
author: rpetrusha
ms.author: ronpet
ms.workload:
- dotnet
- dotnetcore
ms.openlocfilehash: 50dee427913e1ec94a06f1202966bb0f7f5f2099
ms.sourcegitcommit: ad99773e5e45068ce03b99518008397e1299e0d1
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/22/2018
ms.locfileid: "46696423"
---
# <a name="handling-io-errors-in-net"></a><span data-ttu-id="ed4cc-102">. NET'te g/ç hataları işleme</span><span class="sxs-lookup"><span data-stu-id="ed4cc-102">Handling I/O errors in .NET</span></span>

<span data-ttu-id="ed4cc-103">Herhangi bir yöntem çağrısında atılan özel durumların yanı sıra (gibi bir <xref:System.OutOfMemoryException> bir sistem denebilecek veya bir <xref:System.NullReferenceException> Programcı hatası nedeniyle), .NET dosya sistemi yöntemleri aşağıdaki özel durum throw:</span><span class="sxs-lookup"><span data-stu-id="ed4cc-103">In addition to the exceptions that can be thrown in any method call (such as an <xref:System.OutOfMemoryException> when a system is stressed or an <xref:System.NullReferenceException> due to programmer error), .NET file system methods can throw the following exceptions:</span></span>

- <span data-ttu-id="ed4cc-104"><xref:System.IO.IOException?displayProperty=nameWithType>, tüm temel sınıfını <xref:System.IO> özel durum türleri.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-104"><xref:System.IO.IOException?displayProperty=nameWithType>, the base class of all <xref:System.IO> exception types.</span></span> <span data-ttu-id="ed4cc-105">Hataları olan dönüş kodları işletim sisteminden herhangi bir özel durum türü için doğrudan eşleme yoksa oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-105">It is thrown for errors whose return codes from the operating system don't directly map to any other exception type.</span></span>
- <span data-ttu-id="ed4cc-106"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-106"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ed4cc-107"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-107"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ed4cc-108"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-108"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ed4cc-109"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-109"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ed4cc-110"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-110"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ed4cc-111"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-111"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ed4cc-112"><xref:System.ArgumentException?displayProperty=nameWithType>, .NET Framework ve .NET Core 2.0 ve önceki sürümlerde geçersiz yol karakterleri için oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-112"><xref:System.ArgumentException?displayProperty=nameWithType>, which is thrown for invalid path characters on .NET Framework and on .NET Core 2.0 and previous versions.</span></span>
- <span data-ttu-id="ed4cc-113"><xref:System.NotSupportedException?displayProperty=nameWithType>, .NET Framework'teki geçersiz iki nokta üst üste için oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-113"><xref:System.NotSupportedException?displayProperty=nameWithType>, which is thrown for invalid colons in .NET Framework.</span></span>
- <span data-ttu-id="ed4cc-114"><xref:System.Security.SecurityException?displayProperty=nameWithType>, .NET Framework yalnızca gerekli izinleri yetersiz sınırlı güvende çalışan uygulamalar için oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-114"><xref:System.Security.SecurityException?displayProperty=nameWithType>, which is thrown for applications running in limited trust that lack the necessary permissions on .NET Framework only.</span></span> <span data-ttu-id="ed4cc-115">(Tam güven .NET Framework varsayılandır.)</span><span class="sxs-lookup"><span data-stu-id="ed4cc-115">(Full trust is the default on .NET Framework.)</span></span>

## <a name="mapping-error-codes-to-exceptions"></a><span data-ttu-id="ed4cc-116">Hata kodları için özel durumları eşleme</span><span class="sxs-lookup"><span data-stu-id="ed4cc-116">Mapping error codes to exceptions</span></span>

<span data-ttu-id="ed4cc-117">Dosya sistemi olan bir işletim sistemi kaynağı olduğundan, .NET Core ve .NET Framework g/ç yöntemlerinden temel işletim sistemi çağrı sarılır.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-117">Because the file system is an operating system resource, I/O methods in both .NET Core and .NET Framework wrap calls to the underlying operating system.</span></span> <span data-ttu-id="ed4cc-118">İşletim sistemi tarafından yürütülen kodda g/ç hata oluştuğunda işletim sistemi hata bilgileri için .NET g/ç yöntemi döndürür.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-118">When an I/O error occurs in code executed by the operating system, the operating system returns error information to the .NET I/O method.</span></span> <span data-ttu-id="ed4cc-119">Yöntemi, ardından hata bilgileri, genellikle bir hata kodu biçiminde bir .NET özel durum türü çevirir.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-119">The method then translates the error information, typically in the form of an error code, into a .NET exception type.</span></span> <span data-ttu-id="ed4cc-120">Çoğu durumda, bunu doğrudan ilgili özel durum türünü hata kodu çevirerek yapar; herhangi bir özel eşleme yöntem çağrısının bağlama göre hata gerçekleştirmez.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-120">In most cases, it does this by directly translating the error code into its corresponding exception type; it does not perform any special mapping of the error based on the context of the method call.</span></span>

<span data-ttu-id="ed4cc-121">Örneğin, Windows işletim sisteminde bir yöntem çağrısının dönen hata kodunu `ERROR_FILE_NOT_FOUND` (veya 0x02) eşleyen bir <xref:System.IO.FileNotFoundException>ve hata kodunu `ERROR_PATH_NOT_FOUND` (veya 0x03) eşleyen bir <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-121">For example, on the Windows operating system, a method call that returns an error code of `ERROR_FILE_NOT_FOUND` (or 0x02) maps to a <xref:System.IO.FileNotFoundException>, and an error code of `ERROR_PATH_NOT_FOUND` (or 0x03) maps to a <xref:System.IO.DirectoryNotFoundException>.</span></span>

<span data-ttu-id="ed4cc-122">Ancak, işletim sistemi altında belirli hata kodlarını döndürür kesin koşulları genellikle belgelenmemiş ya da kötü belgelenmiş.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-122">However, the precise conditions under which the operating system returns particular error codes is often undocumented or poorly documented.</span></span> <span data-ttu-id="ed4cc-123">Sonuç olarak, beklenmeyen özel durum ortaya çıkabilir.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-123">As a result, unexpected exceptions can occur.</span></span> <span data-ttu-id="ed4cc-124">Bir dosya yerine bir dizin ile çalıştığınızdan, örneğin, söz konusu için bir geçersiz dizin yolu sağlama beklediğiniz <xref:System.IO.DirectoryInfo.%23ctor%2A?displayProperty=nameWithType> Oluşturucusu oluşturur bir <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-124">For example, because you are working with a directory rather than a file, you would expect that providing an invalid directory path to the <xref:System.IO.DirectoryInfo.%23ctor%2A?displayProperty=nameWithType> constructor throws a <xref:System.IO.DirectoryNotFoundException>.</span></span> <span data-ttu-id="ed4cc-125">Ancak, bu da oluşturabildiğini varsaymasını bir <xref:System.IO.FileNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-125">However, it may also throw a <xref:System.IO.FileNotFoundException>.</span></span>

## <a name="exception-handling-in-io-operations"></a><span data-ttu-id="ed4cc-126">Özel durum işleme g/ç işlemleri</span><span class="sxs-lookup"><span data-stu-id="ed4cc-126">Exception handling in I/O operations</span></span>

<span data-ttu-id="ed4cc-127">İşletim sisteminde bu olmasının nedeniyle (örneğin, Örneğimizdeki bulunamadı hatası dizin) aynı özel durumları atma sınıfın tamamı g/ç özel durumların herhangi biri, g/ç yöntemi neden olabilir.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-127">Because of this reliance on the operating system, identical exception conditions (such as the directory not found error in our example) can result in an I/O method throwing any one of the entire class of I/O exceptions.</span></span> <span data-ttu-id="ed4cc-128">G/ç API'leri çağrılırken, kodunuzu çoğunu veya tümünü bu özel durumları işlemek için aşağıdaki tabloda gösterildiği gibi hazırlıklı olmalıdır, yani:</span><span class="sxs-lookup"><span data-stu-id="ed4cc-128">This means that, when calling I/O APIs, your code should be prepared to handle most or all of these exceptions, as shown in the following table:</span></span>

| <span data-ttu-id="ed4cc-129">Özel durum türü</span><span class="sxs-lookup"><span data-stu-id="ed4cc-129">Exception type</span></span> | <span data-ttu-id="ed4cc-130">.NET Core</span><span class="sxs-lookup"><span data-stu-id="ed4cc-130">.NET Core</span></span> | <span data-ttu-id="ed4cc-131">.NET Framework</span><span class="sxs-lookup"><span data-stu-id="ed4cc-131">.NET Framework</span></span> |
|---|---|---|
| <xref:System.IO.IOException> | <span data-ttu-id="ed4cc-132">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-132">Yes</span></span> | <span data-ttu-id="ed4cc-133">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-133">Yes</span></span> |
| <xref:System.IO.FileNotFoundException> | <span data-ttu-id="ed4cc-134">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-134">Yes</span></span> | <span data-ttu-id="ed4cc-135">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-135">Yes</span></span> |
| <xref:System.IO.DirectoryNotFoundException> | <span data-ttu-id="ed4cc-136">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-136">Yes</span></span> | <span data-ttu-id="ed4cc-137">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-137">Yes</span></span> |
| <xref:System.IO.DriveNotFoundException?> | <span data-ttu-id="ed4cc-138">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-138">Yes</span></span> | <span data-ttu-id="ed4cc-139">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-139">Yes</span></span> |
| <xref:System.IO.PathTooLongException> | <span data-ttu-id="ed4cc-140">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-140">Yes</span></span> | <span data-ttu-id="ed4cc-141">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-141">Yes</span></span> |
| <xref:System.OperationCanceledException> | <span data-ttu-id="ed4cc-142">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-142">Yes</span></span> | <span data-ttu-id="ed4cc-143">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-143">Yes</span></span> |
| <xref:System.UnauthorizedAccessException> | <span data-ttu-id="ed4cc-144">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-144">Yes</span></span> | <span data-ttu-id="ed4cc-145">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-145">Yes</span></span> |
| <xref:System.ArgumentException> | <span data-ttu-id="ed4cc-146">.NET core 2.0 ve daha önceki</span><span class="sxs-lookup"><span data-stu-id="ed4cc-146">.NET Core 2.0 and earlier</span></span>| <span data-ttu-id="ed4cc-147">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-147">Yes</span></span> |
| <xref:System.NotSupportedException> | <span data-ttu-id="ed4cc-148">Hayır</span><span class="sxs-lookup"><span data-stu-id="ed4cc-148">No</span></span> | <span data-ttu-id="ed4cc-149">Evet</span><span class="sxs-lookup"><span data-stu-id="ed4cc-149">Yes</span></span> |
| <xref:System.Security.SecurityException> | <span data-ttu-id="ed4cc-150">Hayır</span><span class="sxs-lookup"><span data-stu-id="ed4cc-150">No</span></span> | <span data-ttu-id="ed4cc-151">Yalnızca sınırlı güven</span><span class="sxs-lookup"><span data-stu-id="ed4cc-151">Limited trust only</span></span> |

## <a name="handling-ioexception"></a><span data-ttu-id="ed4cc-152">Ioexception işleme</span><span class="sxs-lookup"><span data-stu-id="ed4cc-152">Handling IOException</span></span>

<span data-ttu-id="ed4cc-153">Özel durumları için temel sınıf olarak <xref:System.IO> ad alanı, <xref:System.IO.IOException> bir önceden tanımlanmış özel durum türüyle eşleşmediği herhangi bir hata kodu için oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-153">As the base class for exceptions in the <xref:System.IO> namespace, <xref:System.IO.IOException> is also thrown for any error code that does not map to a predefined exception type.</span></span> <span data-ttu-id="ed4cc-154">Bu, tüm g/ç işlemi tarafından muhtemel anlamına gelir.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-154">This means that it can be thrown by any I/O operation.</span></span>

> [!IMPORTANT]
> <span data-ttu-id="ed4cc-155">Çünkü <xref:System.IO.IOException> temel sınıf içindeki diğer özel durum türleri <xref:System.IO> ad alanı, ele içinde bir `catch` diğer miyim GÇ ile ilgili özel durumlar tabi sonra engelleyin.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-155">Because <xref:System.IO.IOException> is the base class of the other exception types in the <xref:System.IO> namespace, you should handle in a `catch` block after you've handled the other I/O-related exceptions.</span></span>

<span data-ttu-id="ed4cc-156">Ayrıca, .NET Core 2.1 ile başlayarak, doğrulama denetimlerini (örneğin, geçersiz karakterler bir yolda mevcut olmadığından emin olun) yolu doğruluk kaldırıldı ve çalışma zamanı bir işletim sistemi hata kodu eşlenmiş bir özel durum oluşturduğunda yerine kendi doğrulama kodu.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-156">In addition, starting with .NET Core 2.1, validation checks for path correctness (for example, to ensure that invalid characters are not present in a path) have been removed, and the runtime throws an exception mapped from an operating system error code rather than from its own validation code.</span></span> <span data-ttu-id="ed4cc-157">Büyük olasılıkla özel durum oluşturulmasına bu durumda, bir <xref:System.IO.IOException>, ancak herhangi bir özel durum türü de durum oluşturulabilir.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-157">The most likely exception to be thrown in this case is an <xref:System.IO.IOException>, although any other exception type could also be thrown.</span></span>

<span data-ttu-id="ed4cc-158">Kod, özel durum işleme içinde size her zaman işlemesi gerekir, Not <xref:System.IO.IOException> son.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-158">Note that, in your exception handling code, you should always handle the <xref:System.IO.IOException> last.</span></span> <span data-ttu-id="ed4cc-159">Aksi takdirde, diğer GÇ özel durumların tüm temel sınıfı olduğundan, türetilen sınıfların catch blokları değerlendirilmez.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-159">Otherwise, because it is the base class of all other IO exceptions, the catch blocks of derived classes will not be evaluated.</span></span>

<span data-ttu-id="ed4cc-160">Durumunda, bir <xref:System.IO.IOException>, ek hata bilgileri alabilirsiniz [IOException.HResult](xref:System.Exception.HResult) özelliği.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-160">In the case of an <xref:System.IO.IOException>, you can get additional error information from the [IOException.HResult](xref:System.Exception.HResult) property.</span></span> <span data-ttu-id="ed4cc-161">Bir Win32 hata kodunu HResult değerini dönüştürmek için üst 16 bit 32-bit değerinin Şerit.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-161">To convert the HResult value to a Win32 error code, you strip out the upper 16 bits of the 32-bit value.</span></span> <span data-ttu-id="ed4cc-162">Aşağıdaki tablo, içinde sarmalanmış hata kodlarını listeler bir <xref:System.IO.IOException>.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-162">The following table lists error codes that may be wrapped in an <xref:System.IO.IOException>.</span></span>

| <span data-ttu-id="ed4cc-163">HResult</span><span class="sxs-lookup"><span data-stu-id="ed4cc-163">HResult</span></span> | <span data-ttu-id="ed4cc-164">Sabit</span><span class="sxs-lookup"><span data-stu-id="ed4cc-164">Constant</span></span> | <span data-ttu-id="ed4cc-165">Açıklama</span><span class="sxs-lookup"><span data-stu-id="ed4cc-165">Description</span></span> |
| --- | --- | --- |
| <span data-ttu-id="ed4cc-166">ERROR_SHARING_VIOLATION</span><span class="sxs-lookup"><span data-stu-id="ed4cc-166">ERROR_SHARING_VIOLATION</span></span> | <span data-ttu-id="ed4cc-167">32</span><span class="sxs-lookup"><span data-stu-id="ed4cc-167">32</span></span> | <span data-ttu-id="ed4cc-168">Dosya adı eksik ya da dosya veya dizin kullanılır.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-168">The file name is missing, or the file or directory is in use.</span></span> |
| <span data-ttu-id="ed4cc-169">ERROR_FILE_EXISTS</span><span class="sxs-lookup"><span data-stu-id="ed4cc-169">ERROR_FILE_EXISTS</span></span> | <span data-ttu-id="ed4cc-170">80</span><span class="sxs-lookup"><span data-stu-id="ed4cc-170">80</span></span> | <span data-ttu-id="ed4cc-171">Dosya zaten var.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-171">The file already exists.</span></span> |
| <span data-ttu-id="ed4cc-172">ERROR_INVALID_PARAMETER</span><span class="sxs-lookup"><span data-stu-id="ed4cc-172">ERROR_INVALID_PARAMETER</span></span> | <span data-ttu-id="ed4cc-173">87</span><span class="sxs-lookup"><span data-stu-id="ed4cc-173">87</span></span> | <span data-ttu-id="ed4cc-174">Yönteme sağlanan bağımsız değişken geçersiz.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-174">An argument supplied to the method is invalid.</span></span> |
| <span data-ttu-id="ed4cc-175">ERROR_ALREADY_EXISTS</span><span class="sxs-lookup"><span data-stu-id="ed4cc-175">ERROR_ALREADY_EXISTS</span></span> | <span data-ttu-id="ed4cc-176">183</span><span class="sxs-lookup"><span data-stu-id="ed4cc-176">183</span></span> | <span data-ttu-id="ed4cc-177">Dosya veya dizin zaten var.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-177">The file or directory already exists.</span></span> |

<span data-ttu-id="ed4cc-178">Bunları kullanarak işleyebilir bir `When` yan tümcesinde aşağıdaki örnekte gösterildiği gibi bir catch deyimi.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-178">You can handle these using a `When` clause in a catch statement, as the following example shows.</span></span>

[!code-csharp[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/cs/io-exceptions.cs)]
[!code-vb[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/vb/io-exceptions.vb)]

## <a name="see-also"></a><span data-ttu-id="ed4cc-179">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="ed4cc-179">See also</span></span>

- [<span data-ttu-id="ed4cc-180">İşleme ve .NET özel durumları atma</span><span class="sxs-lookup"><span data-stu-id="ed4cc-180">Handling and throwing exceptions in .NET</span></span>](../exceptions/index.md)
- [<span data-ttu-id="ed4cc-181">Özel durum işleme (görev paralel kitaplığı)</span><span class="sxs-lookup"><span data-stu-id="ed4cc-181">Exception handling (Task Parallel Library)</span></span>](../parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="ed4cc-182">Özel durumlar için en iyi yöntemler</span><span class="sxs-lookup"><span data-stu-id="ed4cc-182">Best practices for exceptions</span></span>](../exceptions/best-practices-for-exceptions.md)
- [<span data-ttu-id="ed4cc-183">Bir catch bloğunda belirli özel durumları kullanma</span><span class="sxs-lookup"><span data-stu-id="ed4cc-183">How to use specific exceptions in a catch block</span></span>](../exceptions/how-to-use-specific-exceptions-in-a-catch-block.md)