---
title: "Özel Durum İşleme (C# Programlama Kılavuzu)"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], handling
ms.assetid: b4e4ecf2-b907-4e58-891f-2563762258e9
caps.latest.revision: "24"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: dfdd8b8bdd89e4253dfc1afebc1e78140b121dd6
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 11/21/2017
---
# <a name="exception-handling-c-programming-guide"></a><span data-ttu-id="ca30d-102">Özel Durum İşleme (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="ca30d-102">Exception Handling (C# Programming Guide)</span></span>
<span data-ttu-id="ca30d-103">A [deneyin](../../../csharp/language-reference/keywords/try-catch.md) blok C# programcıları için bir özel durum tarafından etkilenebilir bölüm kod tarafından kullanılır.</span><span class="sxs-lookup"><span data-stu-id="ca30d-103">A [try](../../../csharp/language-reference/keywords/try-catch.md) block is used by C# programmers to partition code that might be affected by an exception.</span></span> <span data-ttu-id="ca30d-104">İlişkili [catch](../../../csharp/language-reference/keywords/try-catch.md) blokları, sonuçta elde edilen özel durumları işlemek için kullanılır.</span><span class="sxs-lookup"><span data-stu-id="ca30d-104">Associated [catch](../../../csharp/language-reference/keywords/try-catch.md) blocks are used to handle any resulting exceptions.</span></span> <span data-ttu-id="ca30d-105">A [son](../../../csharp/language-reference/keywords/try-finally.md) blok olsun veya olmasın bir özel durum bağımsız olarak çalıştırma kodunu içerir `try` içinde ayrılan kaynakları serbest bırakma gibi blok `try` bloğu.</span><span class="sxs-lookup"><span data-stu-id="ca30d-105">A [finally](../../../csharp/language-reference/keywords/try-finally.md) block contains code that is run regardless of whether or not an exception is thrown in the `try` block, such as releasing resources that are allocated in the `try` block.</span></span> <span data-ttu-id="ca30d-106">A `try` blok gerektiren bir veya daha fazla ilişkili `catch` blokları, veya bir `finally` engelleme veya her ikisi de.</span><span class="sxs-lookup"><span data-stu-id="ca30d-106">A `try` block requires one or more associated `catch` blocks, or a `finally` block, or both.</span></span>  
  
 <span data-ttu-id="ca30d-107">Aşağıdaki örneklerde gösterildiği bir `try-catch` deyimi, bir `try-finally` deyimi ve bir `try-catch-finally` deyimi.</span><span class="sxs-lookup"><span data-stu-id="ca30d-107">The following examples show a `try-catch` statement, a `try-finally` statement, and a `try-catch-finally` statement.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#6](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/exception-handling_1.cs)]  
  
 [!code-csharp[csProgGuideExceptions#7](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/exception-handling_2.cs)]  
  
 [!code-csharp[csProgGuideExceptions#8](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/exception-handling_3.cs)]  
  
 <span data-ttu-id="ca30d-108">A `try` olmadan engelleme bir `catch` veya `finally` blok derleyici hatası neden olur.</span><span class="sxs-lookup"><span data-stu-id="ca30d-108">A `try` block without a `catch` or `finally` block causes a compiler error.</span></span>  
  
## <a name="catch-blocks"></a><span data-ttu-id="ca30d-109">Catch blokları</span><span class="sxs-lookup"><span data-stu-id="ca30d-109">Catch Blocks</span></span>  
 <span data-ttu-id="ca30d-110">A `catch` blok yakalamak için özel durum türünü belirtebilirsiniz.</span><span class="sxs-lookup"><span data-stu-id="ca30d-110">A `catch` block can specify the type of exception to catch.</span></span> <span data-ttu-id="ca30d-111">Tür belirtimi adlı bir *özel durum filtresi*.</span><span class="sxs-lookup"><span data-stu-id="ca30d-111">The type specification is called an *exception filter*.</span></span> <span data-ttu-id="ca30d-112">Özel durum türü türetilmiş <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="ca30d-112">The exception type should be derived from <xref:System.Exception>.</span></span> <span data-ttu-id="ca30d-113">Genel olarak, belirtmeyin <xref:System.Exception> özel durum filtre olarak ya da bir durum içinde tüm özel durumları işleme bilmiyorsanız `try` engelleme veya dahil ettiyseniz bir [throw](../../../csharp/language-reference/keywords/throw.md) deyimi, sonunda`catch`bloğu.</span><span class="sxs-lookup"><span data-stu-id="ca30d-113">In general, do not specify <xref:System.Exception> as the exception filter unless either you know how to handle all exceptions that might be thrown in the `try` block, or you have included a [throw](../../../csharp/language-reference/keywords/throw.md) statement at the end of your `catch` block.</span></span>  
  
 <span data-ttu-id="ca30d-114">Birden çok `catch` farklı özel durum filtreleri bloklarla zincirleme yapılabilir birlikte.</span><span class="sxs-lookup"><span data-stu-id="ca30d-114">Multiple `catch` blocks with different exception filters can be chained together.</span></span> <span data-ttu-id="ca30d-115">`catch` Blokları değerlendirilir üstten alta kodunuzu, ancak yalnızca bir `catch` blok oluşturulan her bir özel durum için gerçekleştirilir.</span><span class="sxs-lookup"><span data-stu-id="ca30d-115">The `catch` blocks are evaluated from top to bottom in your code, but only one `catch` block is executed for each exception that is thrown.</span></span> <span data-ttu-id="ca30d-116">İlk `catch` türünü tam ya da oluşturulan özel durum, bir taban sınıf belirtir blok gerçekleştirilir.</span><span class="sxs-lookup"><span data-stu-id="ca30d-116">The first `catch` block that specifies the exact type or a base class of the thrown exception is executed.</span></span> <span data-ttu-id="ca30d-117">Yoksa `catch` blok belirtir eşleşen bir özel durum filtresi bir `catch` bir filtre yok blok seçilirse, bir deyimde mevcut değilse.</span><span class="sxs-lookup"><span data-stu-id="ca30d-117">If no `catch` block specifies a matching exception filter, a `catch` block that does not have a filter is selected, if one is present in the statement.</span></span> <span data-ttu-id="ca30d-118">Konumlandırmak önemlidir `catch` en (diğer bir deyişle, en çok türetilen) özel durum bloklarla türleri ilk.</span><span class="sxs-lookup"><span data-stu-id="ca30d-118">It is important to position `catch` blocks with the most specific (that is, the most derived) exception types first.</span></span>  
  
 <span data-ttu-id="ca30d-119">Aşağıdaki koşullar doğru olduğunda özel durumlarını yakalama:</span><span class="sxs-lookup"><span data-stu-id="ca30d-119">You should catch exceptions when the following conditions are true:</span></span>  
  
-   <span data-ttu-id="ca30d-120">Bir iyi, özel durum ve kullanıcıdan, catch zaman yeni bir dosya adı girin gibi belirli bir kurtarma, uygulayabilirsiniz neden anlama sahip bir <xref:System.IO.FileNotFoundException> nesnesi.</span><span class="sxs-lookup"><span data-stu-id="ca30d-120">You have a good understanding of why the exception might be thrown, and you can implement a specific recovery, such as prompting the user to enter a new file name when you catch a <xref:System.IO.FileNotFoundException> object.</span></span>  
  
-   <span data-ttu-id="ca30d-121">Oluşturun ve yeni, daha belirli bir özel durum.</span><span class="sxs-lookup"><span data-stu-id="ca30d-121">You can create and throw a new, more specific exception.</span></span>  
  
     [!code-csharp[csProgGuideExceptions#9](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/exception-handling_4.cs)]  
  
-   <span data-ttu-id="ca30d-122">Kısmen, ek işleme için'a geçirmeden önce özel bir durumu işlemek istediğiniz.</span><span class="sxs-lookup"><span data-stu-id="ca30d-122">You want to partially handle an exception before passing it on for additional handling.</span></span> <span data-ttu-id="ca30d-123">Aşağıdaki örnekte, bir `catch` bloğu, özel durum yeniden atmadan önce bir hata günlüğü için bir giriş eklemek için kullanılır.</span><span class="sxs-lookup"><span data-stu-id="ca30d-123">In the following example, a `catch` block is used to add an entry to an error log before re-throwing the exception.</span></span>  
  
     [!code-csharp[csProgGuideExceptions#10](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/exception-handling_5.cs)]  
  
## <a name="finally-blocks"></a><span data-ttu-id="ca30d-124">Finally blokları</span><span class="sxs-lookup"><span data-stu-id="ca30d-124">Finally Blocks</span></span>  
 <span data-ttu-id="ca30d-125">A `finally` bloğu içinde gerçekleştirilen eylemler temizlemek etkinleştirir bir `try` bloğu.</span><span class="sxs-lookup"><span data-stu-id="ca30d-125">A `finally` block enables you to clean up actions that are performed in a `try` block.</span></span> <span data-ttu-id="ca30d-126">Varsa, `finally` blok sonra sonuncu yürütür `try` bloğu ve herhangi bir eşleşen `catch` bloğu.</span><span class="sxs-lookup"><span data-stu-id="ca30d-126">If present, the `finally` block executes last, after the `try` block and any matched `catch` block.</span></span> <span data-ttu-id="ca30d-127">A `finally` engelleme her zaman çalışır, bağımsız olarak, bir özel durum veya bir `catch` özel durum türü eşleşen blok bulundu.</span><span class="sxs-lookup"><span data-stu-id="ca30d-127">A `finally` block always runs, regardless of whether an exception is thrown or a `catch` block matching the exception type is found.</span></span>  
  
 <span data-ttu-id="ca30d-128">`finally` Bloğu, dosya akışlar, veritabanı bağlantıları gibi kaynakları serbest bırakmak için kullanılabilir ve grafik işleme atık toplayıcı çalışma zamanında nesneleri sonlandırmaya beklemeden.</span><span class="sxs-lookup"><span data-stu-id="ca30d-128">The `finally` block can be used to release resources such as file streams, database connections, and graphics handles without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="ca30d-129">Bkz: [deyimiyle](../../../csharp/language-reference/keywords/using-statement.md) daha fazla bilgi için.</span><span class="sxs-lookup"><span data-stu-id="ca30d-129">See [using Statement](../../../csharp/language-reference/keywords/using-statement.md) for more information.</span></span>  
  
 <span data-ttu-id="ca30d-130">Aşağıdaki örnekte, `finally` bloğu içinde açılmış bir dosyayı kapatma için kullanılan `try` bloğu.</span><span class="sxs-lookup"><span data-stu-id="ca30d-130">In the following example, the `finally` block is used to close a file that is opened in the `try` block.</span></span> <span data-ttu-id="ca30d-131">Dosya kapatılmadan önce dosya tanıtıcısı durumunu işaretli olduğuna dikkat edin.</span><span class="sxs-lookup"><span data-stu-id="ca30d-131">Notice that the state of the file handle is checked before the file is closed.</span></span> <span data-ttu-id="ca30d-132">Varsa `try` blok dosyayı açamıyor, dosya tanıtıcısı hala değerine sahip `null` ve `finally` blok kapatmak deneyin değil.</span><span class="sxs-lookup"><span data-stu-id="ca30d-132">If the `try` block cannot open the file, the file handle still has the value `null` and the `finally` block does not try to close it.</span></span> <span data-ttu-id="ca30d-133">Alternatif olarak, dosya başarıyla açılırsa `try` bloğu `finally` blok açık dosyayı kapatır.</span><span class="sxs-lookup"><span data-stu-id="ca30d-133">Alternatively, if the file is opened successfully in the `try` block, the `finally` block closes the open file.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#11](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/exception-handling_6.cs)]  
  
## <a name="c-language-specification"></a><span data-ttu-id="ca30d-134">C# Dil Belirtimi</span><span class="sxs-lookup"><span data-stu-id="ca30d-134">C# Language Specification</span></span>  
 [!INCLUDE[CSharplangspec](~/includes/csharplangspec-md.md)]  
  
## <a name="see-also"></a><span data-ttu-id="ca30d-135">Ayrıca Bkz.</span><span class="sxs-lookup"><span data-stu-id="ca30d-135">See Also</span></span>  
 [<span data-ttu-id="ca30d-136">C# başvurusu</span><span class="sxs-lookup"><span data-stu-id="ca30d-136">C# Reference</span></span>](../../../csharp/language-reference/index.md)  
 [<span data-ttu-id="ca30d-137">C# programlama kılavuzu</span><span class="sxs-lookup"><span data-stu-id="ca30d-137">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)  
 [<span data-ttu-id="ca30d-138">Özel durumlar ve özel durum işleme</span><span class="sxs-lookup"><span data-stu-id="ca30d-138">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)  
 [<span data-ttu-id="ca30d-139">try-catch</span><span class="sxs-lookup"><span data-stu-id="ca30d-139">try-catch</span></span>](../../../csharp/language-reference/keywords/try-catch.md)  
 [<span data-ttu-id="ca30d-140">try-finally</span><span class="sxs-lookup"><span data-stu-id="ca30d-140">try-finally</span></span>](../../../csharp/language-reference/keywords/try-finally.md)  
 [<span data-ttu-id="ca30d-141">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="ca30d-141">try-catch-finally</span></span>](../../../csharp/language-reference/keywords/try-catch-finally.md)  
 [<span data-ttu-id="ca30d-142">using deyimi</span><span class="sxs-lookup"><span data-stu-id="ca30d-142">using Statement</span></span>](../../../csharp/language-reference/keywords/using-statement.md)
