---
title: Derleyici Hatası CS0103
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: error-reference
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
caps.latest.revision: 13
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: be7805c105d1d513dc83c44c430b02771c63db71
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-error-cs0103"></a>Derleyici Hatası CS0103
'Tanımlayıcı' adı geçerli bağlamda mevcut değil  
  
 Sınıfında, var olmayan bir ad kullanmak için bir girişimde bulunuldu [ad alanı](../../../csharp/language-reference/keywords/namespace.md), veya kapsam. Adının yazımını denetleyin ve kullanarak denetleyin yönergeleri ve derleme başvurularını kullanmaya çalıştığınız adı kullanılabilir olduğundan emin olun.  
  
 Bir değişkende bir döngü bildirirseniz bu hata sık sık oluşur veya `try` veya `if` engelleme ve ardından kapsayan bir kod bloğu ya da ayrı kod bloğu erişmek aşağıdaki örnekte gösterildiği gibi çalışır.  
  
```csharp  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```  
  
 Aşağıdaki örnek hata çözümler.  
  
```csharp  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```
